ActividadDjango/Actividad2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls'))
]

ActividadDjango/Apps/home/urls.py
from Apps.home.views import HomeView
from django.contrib import admin
from django.urls import path
from .views import HomeView,CreditosView,EstudiantesView,AdministradoresView,AcercadeView,ContactoView
from .views import ListarEstudiante, CrearEstudianteView,CrearAdminView
app_name = 'home'

urlpatterns = [
    path('index/', HomeView.as_view(), name='home'),
    path('creditos/', CreditosView.as_view(), name='creditos'),
    path('estudiantes/', EstudiantesView.as_view(), name='estudiantes'),
    path('administradores/', AdministradoresView.as_view(), name='administradores'),
    path('acercade/', AcercadeView.as_view(), name='acercade'),
    path('contacto/', ContactoView.as_view(), name='contacto'),
    path('listest/', ListarEstudiante.as_view(), name='listar_est'),
    path('crear/', CrearEstudianteView.as_view(), name='crear'),
    path('crear_admin/', CrearAdminView.as_view(), name='Crear'),
]

ActividadDjango/Apps/home/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    doc = (
        ('D','DPI'),
        ('C','CEDULA'),
    )
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200)
    nacimiento = models.DateField()
    tipo = models.ForeignKey(
        'TipoCliente',
        on_delete=models.CASCADE,
        default=1
        )
    documento = models.CharField(
        max_length=20,
        choices=doc,
        default='C',)
    creacion = models.DateField(auto_now_add=True)
    actualizacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)

class TipoCliente(models.Model):
      tipo = models.CharField(max_length=50)
      creacion = models.DateField(auto_now_add=True)
      actualizacion = models.DateField(auto_now_add=True)

      def __str__(self):
        return '%s' % (self.tipo)

class Estudiante(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)

class Administradores(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)
    

    

ActividadDjango/Apps/home/forms.py
from django import forms
from .models import Administradores, Estudiante 

class EstudianteForms(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'

class AdministradorForms(forms.ModelForm):
    class Meta:
        model = Administradores
        fields = '__all__'

ActividadDjango/Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView
from .models import Administradores, Estudiante
from .forms import EstudianteForms,AdministradorForms
from django.urls import reverse_lazy
# Create your views here.

class HomeView(TemplateView):
    template_name='index.html'

class CreditosView(TemplateView):
    template_name='creditos.html'

class EstudiantesView(TemplateView):
    template_name='estudiantes.html'

class AdministradoresView(TemplateView):
    template_name='Administradores.html'

class AcercadeView(TemplateView):
    template_name='acercade.html'

class ContactoView(TemplateView):
    template_name='contacto.html'

class ListarEstudiante(ListView):
    template_name = 'listar_est.html'
    model = Estudiante 

    def get_queryset(self):
        return Estudiante.objects.all()

class ListarAdministradores(ListView):
    template_name='administradores.html'
    model = Administradores

class CrearEstudianteView(CreateView):
    template_name = 'crear_estudiante.html'
    form_class = EstudianteForms 
    success_url = reverse_lazy('home:crear')

class CrearAdminView(CreateView):
    template_name = 'crear_admin.html'
    form_class = AdministradorForms 
    success_url = reverse_lazy('home:Crear')

ActividadDjango/Apps/home/templates/acercade.html
{% extends 'base.html' %}

{% block acercade %}
Acerca de
{% endblock%}

ActividadDjango/Apps/home/templates/administradores.html
{% extends 'base.html' %}

{% block Administradores %}

    <table border="2">
        <tr>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Direccion</td>
        </tr>
        {% for adm in object_list %}  
        <tr>
            <td>{{ adm.nombre }}</td>
            <td>{{ adm.apellido }}</td>
            <td>{{ adm.direccion }}</td>
        </tr>
        {% endfor %}
    </table>
    <h2>Crear administrador</h2>
    <a href="{% url 'home:Crear'%}">Crear</a>
{% endblock%}

ActividadDjango/Apps/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700,900" rel="stylesheet">

    <title>Elegance - Creative HTML5 Template</title>
<!--
Elegance Template
https://templatemo.com/tm-528-elegance
-->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/fullpage.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    </head>
    
    <body>
    
    <div id="video">
        <div class="preloader">
            <div class="preloader-bounce">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <header id="header">
            <div class="container-fluid">
                <div class="navbar">
                    <a href="#" id="logo" title="Elegance by TemplateMo">
                        Desarrollo Web UMG
                    </a>
                    <div class="navigation-row">
                        <nav id="navigation">
                            <button type="button" class="navbar-toggle"> <i class="fa fa-bars"></i> </button>
                            <div class="nav-box navbar-collapse">
                                <ul class="navigation-menu nav navbar-nav navbars" id="nav">
                                    <li data-menuanchor="slide01" class="active"><a href="#slide01">Home</a></li>
                                    <li data-menuanchor="slide02"><a href="#slide02">Acerca de</a></li>
                                    <li data-menuanchor="slide03"><a href="{% url 'home:administradores'%}">Administradores</a></li>
                                    <li data-menuanchor="slide04"><a href="{% url 'home:estudiantes'%}">Estudiantes</a></li>
                                    <li data-menuanchor="slide07"><a href="#slide05">Contact Me</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>

        <video autoplay muted loop id="myVideo">
          <source src="{% static 'images/video-bg.mp4' %}" type="video/mp4">
        </video>

        <div id="fullpage" class="fullpage-default">

            <div class="section animated-row" data-section="slide01">
                <div class="section-inner">
                    <div class="welcome-box">
                        <span class="welcome-first animate" data-animate="fadeInUp">Hola, bienvenido</span> {% block titulo %} {% endblock%}
                        <h1 class="welcome-title animate" data-animate="fadeInUp">colegio tacana</h1>
                        <p class="animate" data-animate="fadeInUp">¡Gracias por formar parte de nuestra familia!. </p>
                        <div class="scroll-down next-section animate data-animate="fadeInUp""><img src="{% static 'images/mouse-scroll.png' %}" alt=""><span>Scroll Down</span></div>
                    </div>
                </div>
            </div>

            <div class="section animated-row" data-section="slide02">
                <div class="section-inner">
                    <div class="about-section">
                        <div class="row justify-content-center">
                            <div class="col-lg-8 wide-col-laptop">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="about-contentbox">
                                            <div class="animate" data-animate="fadeInUp">
                                                <span>Acerca de</span> {% block acercade %} {% endblock%}
                                                <h2>Who am i?</h2>
                                                <p>Credits go to <strong>Unsplash</strong> and <strong>Pexels</strong> for photos and video used in this template. Vivamus tincidunt, augue rutrum convallis volutpat, massa lacus tempus leo.</p>
                                            </div>
                                            <div class="facts-list owl-carousel">
                                                <div class="item animate" data-animate="fadeInUp">
                                                    <div class="counter-box">
                                                        <i class="fa fa-trophy counter-icon" aria-hidden="true"></i><span class="count-number">32</span> Awards Won
                                                    </div>
                                                </div>
                                                <div class="item animate" data-animate="fadeInUp">
                                                    <div class="counter-box">
                                                        <i class="fa fa-graduation-cap counter-icon" aria-hidden="true"></i><span class="count-number">4</span> Degrees
                                                    </div>
                                                </div>
                                                <div class="item animate" data-animate="fadeInUp">
                                                    <div class="counter-box">
                                                        <i class="fa fa-desktop counter-icon" aria-hidden="true"></i><span class="count-number">12</span> Working Years
                                                    </div>
                                                </div>
                                                <div class="item animate" data-animate="fadeInUp">
                                                    <div class="counter-box">
                                                        <i class="fa fa-support counter-icon" aria-hidden="true"></i><span class="count-number">6</span> Team Members
                                                    </div>
                                                </div>
                                                <div class="item animate" data-animate="fadeInUp">
                                                    <div class="counter-box">
                                                        <i class="fa fa-certificate counter-icon" aria-hidden="true"></i><span class="count-number">10</span> Certificates
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <figure class="about-img animate" data-animate="fadeInUp"><img src="{% static 'images/profile-girl.jpg' %}" class="rounded" alt=""></figure>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section animated-row" data-section="slide03">
                <div class="section-inner">
                    <div class="row justify-content-center">
                        <div class="col-md-8 wide-col-laptop">
                            <div class="title-block animate" data-animate="fadeInUp">
                                <span></span>{% block Administradores %} {% endblock%}      
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section animated-row" data-section="slide04">
                <div class="section-inner">
                    <div class="row justify-content-center">
                        <div class="col-md-7 wide-col-laptop">
                            <div class="title-block animate" data-animate="fadeInUp">
                                <span></span>{% block Estudiantes %} {% endblock%}   
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           

            <div class="section animated-row" data-section="slide05">
                <div class="section-inner">
                    <div class="row justify-content-center">
                        <div class="col-md-7 wide-col-laptop">
                            <div class="title-block animate" data-animate="fadeInUp">
                                <span>Contact</span>
                                <h2>Get In Touch!</h2>
                            </div>
                            <div class="contact-section">
                                <div class="row">
                                    <div class="col-md-6 animate" data-animate="fadeInUp">
                                        <div class="contact-box">
                                            <div class="contact-row">
                                                <i class="fa fa-map-marker"></i> 123 New Street Here, Wonderful City 10220
                                            </div>
                                            <div class="contact-row">
                                                <i class="fa fa-phone"></i> 090 080 0210
                                            </div>
                                            <div class="contact-row">
                                                <i class="fa fa-envelope"></i> info@company.co
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 animate" data-animate="fadeInUp">
                                        <form id="ajax-contact" method="post" action="#">
                                            <div class="input-field">
                                                <input type="text" class="form-control" name="name" id="name" required placeholder="Name">
                                            </div>
                                            <div class="input-field">
                                                <input type="email" class="form-control" name="email" id="email" required placeholder="Email">
                                            </div>
                                            <div class="input-field">
                                                <textarea class="form-control" name="message" id="message" required placeholder="Message"></textarea>
                                            </div>
                                            <button class="btn" type="submit">Submit</button>
                                        </form>
                                        <div id="form-messages" class="mt-3"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="social-icons">
            <div class="text-right">
                <ul class="social-icons">
                    <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" title="Instagram"><i class="fa fa-behance"></i></a></li>
                </ul>
            </div>
        </div>
    </div>  

    <script src="{% static 'js/jquery.js' %}"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/fullpage.min.js' %}"></script>

    <script src="{% static 'js/scrolloverflow.js' %}"></script>

    <script src="{% static 'js/owl.carousel.min.js' %}"></script>

    <script src="{% static 'js/jquery.inview.min.js' %}"></script>

    <script src="{% static 'js/form.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>


  </body>
</html>

ActividadDjango/Apps/home/templates/contacto.html
{% extends 'base.html' %}

{% block titulo %}
Contacto
{% endblock%}

ActividadDjango/Apps/home/templates/crear_admin.html
{% extends 'base.html' %}
{% block Administradores %}
<h2>Crear administrador</h2>
<form method="POST">
    {% csrf_token %} 
    Nombre {{ form.nombre}}
    Apellido {{ form.apellido}}
    Direccion {{ form.direccion}}
    <input type="submit" name="Guardar"><p>
</form>
<a href="{% url 'home:administradores' %}">Regresar</a>
{% endblock%}

ActividadDjango/Apps/home/templates/crear_estudiante.html
{% extends 'base.html' %}

{% block Estudiantes %}

<h2>Crear estudiante</h2>
<form method="POST">
    {% csrf_token %} 
    Nombre {{ form.nombre}}
    Apellido {{ form.apellido}}
    Direccion {{ form.direccion}}
    <input type="submit" name="Guardar"><p>
</form>
<a href="{% url 'home:estudiantes' %}">Regresar</a>

{% endblock%}

ActividadDjango/Apps/home/templates/creditos.html
{% extends 'base.html' %}

{% block titulo %}
Creditos
{% endblock%}

ActividadDjango/Apps/home/templates/estudiantes.html
{% extends 'base.html' %}

{% block Estudiantes %}

Estudiantes<hr>
<body>

    <table border="2">
        <tr>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Direccion</td>
        </tr>
        {% for est in object_list %}  
        <tr>
            <td>{{ est.nombre }}</td>
            <td>{{ est.apellido }}</td>
            <td>{{ est.direccion }}</td>
        </tr>
        {% endfor %}
    </table>

    <h2>Crear estudiante</h2>
    <a href="{% url 'home:crear'%}">Crear</a>
</body>
{% endblock%}

ActividadDjango/Apps/home/templates/index.html
{% extends 'base.html' %}

{% block titulo %}
Home
{% endblock%}

ActividadDjango/Apps/home/templates/listar_est.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Listar Estudiante</h1>
    <table border="2">
        <tr>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Direccion</td>
        </tr>
        {% for est in object_list %}  
        <tr>
            <td>{{ est.nombre }}</td>
            <td>{{ est.apellido }}</td>
            <td>{{ est.direccion }}</td>
        </tr>
        {% endfor %}
    </table>
    
</body>
</html>